title: "Weddingsite"
description: "Willkommen auf unserer Hochzeitswebsite!"
baseurl: "" # Leer lassen, da deine Seite auf der Hauptdomain läuft
url: "https://rajohochzeit.at" # Deine Domain

# Markdown und Code
markdown: kramdown
highlighter: rouge

# Theme-Optionen (falls Minima Theme verwendet wird)
theme: minima

# Ausschlüsse für den Build-Prozess
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - .gitignore
  - _site
  - .jekyll-cache

# Plugins (optional, wenn benötigt)
plugins:
  - jekyll-feed
